%packages
libreoffice-*
libreoffice-langpack-en
libreoffice-ogltrans
libreoffice-opensymbol-fonts
libreoffice-pdfimport
libreoffice-ure
libreoffice-xsltfilter
libreoffice-draw
evince
verbiste
keepassxc
%end